# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'recast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for recast
	pod 'RecastAI'
  target 'recastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
